id: P006702
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13819
  title: དབུ་མ་ལ་འཇུག་པའི་སྤྱི་དོན་དགོངས་པ་རབ་གསལ་གྱི་རྒྱན།
  author: ''
  volumes:
    5bebcbaae2af4be48491254d98ddcbee:
      image_group_id: I1KG14935
      title: ''
      volume_number: 1
      total_pages: 342
      base_file: v001.txt
